### ISSUE TITLE
Which license?

### ISSUE THREAD

**Issue by ErrCode** [avarghesein/ActiveX.NET#2]
Hi there,

Can you please clarify and assign a license to your project? e.g. MIT? CC0 (public domain)?

Kind Regards,
E

PS: Thank you for this repo! Just begun learning about COM and this project will help me clarify my ideas.

**Comment by avarghesein** [comment]
Probably CC0? 
As I'm using some code excerpts from https://code.msdn.microsoft.com/windowsapps/CSExeCOMServer-3b1c1054, do you need to use a more restrict licensing, replicating the original one attached to this link (MS-LPL)?

**Comment by ErrCode** [comment]
Thank you for getting back and your honesty about the code excerpts from the MS example. 

I’m not a lawyer, but... :)

It seems you feel that those code excerpts could not have come about independently of the link you sent above, so by that assumption (and looking at that license - especially clause 3(D)) it would seem best that this repo also be the same MS-LPL license<strike> or a compatible one</strike>. 

I’m actually surprised after reading the license that they actually seem to restrict use with Windows only or at least not allow anything that isn’t Microsoft’s platforms. 

*Edit: After reading that clause again, I realised it actually said "If you distribute any portion of the software in source code form, you may do so only under this license..." (so not even a compatible license is permitted with relation to source code).

**Comment by ErrCode** [comment]
I haven't done a side-by-side comparison of what code excerpts you're referring to, but if the code excerpts are reproduced verbatim from the MS example that you linked, then it would seem that the MS-LPL license is the only license you could legally use for this repo.

Somewhat regret that I asked this. Sorry :/

**Comment by avarghesein** [comment]
Reg >>if the code excerpts are reproduced verbatim from the MS example that you linked;

Its not an exact excerpt but rearranged and most variables are renamed. Still its better to use MS-LPL, and I presume it wont restrict you to explore it further.

Thank you for your response.

eg: (file: /Source/ActiveX.NET/ActiveX.NET.Server/ActiveXServerContext.cs)

 uint comRegCookie;

                Guid clsidSimpleObj = comServer.ClassID;

                // Register the SimpleObject class object
                hResult = ActiveXNative.CoRegisterClassObject(
                    ref clsidSimpleObj,                 // CLSID to be registered
                    new DefaultActiveXFactory(comServer,_comServers),     // Class factory
                    CLSCTX.LOCAL_SERVER,                // Context to run
                    REGCLS.MULTIPLEUSE | REGCLS.SUSPENDED,
                    out comRegCookie);

                if (hResult != 0)
                {
                    throw new ApplicationException("CoRegisterClassObject failed w/err 0x" + hResult.ToString("X"));
                }
                else
                {
                    _registrationCookies.Add(comRegCookie);
                }

**Comment by avarghesein** [comment]
Added MIT License. That's seems more appropriate in this case.
https://github.com/avarghesein/ActiveX.NET/blob/master/LICENSE
