### ISSUE TITLE
RegasmRegisterLocalServer Not Invoked?

### ISSUE THREAD

**Issue by alibeirami** [avarghesein/ActiveX.NET#4]
Hi,
Reading source file containing **RegasmRegisterLocalServer** function, I've got the impression that **InprocServer32** Registry key should be replaced by a **LocalServer32** key. I added the following to the class I would have wanted to register as out of process server:

`[ClassInterface(ClassInterfaceType.None)]`
`[ComSourceInterfaces(typeof(IUDEvents))]`
`[Guid(GUIDs.GUID100), ComVisible(true)]`
`[ActiveXServer(CoClassType = typeof(UD), PrimaryInterface = typeof(IUD))]`
`public class UD : IUD`

and ran ActiveX.Net.Server.exe with /regserver flag. Type is registered and I can instantiate it with

`var dqType = Type.GetTypeFromProgID("NameSpace.UD");`
`var ud = (IUD)Activator.CreateInstance(dqType)`

but searching registry for my type, I only find an **InprocServer32** in subkeys. 
Am I missing something?

**EDIT :** 

It was beacuase UD class should inherit ActiveXServerBase too. sorry to bother every one.

**Comment by avarghesein** [comment]
Thank you for confirming
