### ISSUE TITLE
Events with late binding

### ISSUE THREAD

**Issue by viebrix** [avarghesein/ActiveX.NET#7]
Hello,
first many thanks for providing this great project! It helped me a lot to implement an idea I had, but now I'm stuck with calling a client function from comobject event.

What I wanted to do:
I'm using a .NET interop library  which uses a mathematical software named R. The problem with this interop library and R is, that you can only instantiate it one time - because the native R-dll is not threadsafe. Therefore I wanted to implement such com wrapper which wraps some of the functions of the library in an ActiveX exe. Every instance of this com object should generate a new exe which lives in a new process. Every instance finally should link to a new instance of the R-dll. Therefore it finally should be possible to call more than one R instances in a c# program.

So far so good, my idea worked, with your great ActiveX.NET project and a little modification in ActiveXServerContext.cs

What I have modified:
In ActiveXServerContext.cs I changed: 
```
//REGCLS.MULTIPLEUSE| REGCLS.SUSPENDED, to
REGCLS.SINGLEUSE| REGCLS.SUSPENDED,

```
Afterwards every instance opened a new ActiveX.NET.Server.EXE

What I have achieved:
I'm able to instantiate the com object dynamic (late binding) in dotnet and I can call methods and get properties

What I haven't achieved (and here I need your help - please):
I can't add an event handler which fires from server a function in the (dotnet) client. I tried also with your SimpleObject Example, but this also didn't work - maybe I don't understand how events work in Com/dotnet ...
I tried this:

```
public delegate void FloatPropertyChangingEventHandler(float NewValue, ref bool Cancel);
:
:
string progId1 = "ActiveX.NET.Plugin.SimpleObject";
            Type type1 = Type.GetTypeFromProgID(progId1);
            dynamic simpleobject = Activator.CreateInstance(type1);
            tbConsole.AppendText( simpleobject.HelloWorld());
            simpleobject.FloatPropertyChangingEventHandler += new FloatPropertyChangingEventHandler(FloatPropertyChanging);
            simpleobject.FloatProperty = 55.1;

```
But it seems that with dynamic com objects it does not find any information about events. (because there is no typelibrary with ActiveX.NET)
I also tried a lot of other possibilities, like program the event by my own with a com method and providing the client dotnet function pointer to the com server object.  The server should call this function pointer from inside the com server object. But this seems to not work because of not allowed memory access.

Maybe you have an idea what I did wrong or how events can be used with dynamic comobjects. Or maybe you can show me how I can instantiate the ActiveX.NET.Plugin not dynamically.
Many Thanks!
viebrix

**Comment by viebrix** [comment]
Hi @avarghesein, 
I have also tried to get the events with ConnectionPointContainer as described in this   [Article](https://www.codeproject.com/Articles/10262/Receiving-Events-from-late-bound-COM-servers) and this [discussion](https://www.c-sharpcorner.com/forums/com-object-event-handling-problem-with-late-binding)

But still get the error, that interface is not supported.


```
  [ComImport, Guid("014C067E-660D-4d20-9952-CD973CE50436"),
            TypeLibType((short)0x10d0)]
    public interface ISimpleObjectEvents
    {
        [MethodImpl(MethodImplOptions.InternalCall,
    MethodCodeType = MethodCodeType.Runtime),
    DispId(1)]
        void FloatPropertyChanging([In, MarshalAs(UnmanagedType.Interface)]float NewValue, [In] ref bool Cancel);
    }

  [ClassInterface(ClassInterfaceType.None)]
        public sealed class SimpleObjectEvents_SinkHelper : ISimpleObjectEvents
        {
            public void FloatPropertyChanging(float NewValue, ref bool Cancel)
            {
                //Form1.tbConsole.AppendText(NewValue.ToString());
                Console.WriteLine(NewValue.ToString());
            }
        }
```

```
string progId1 = "ActiveX.NET.Plugin.SimpleObject";
            Type type1 = Type.GetTypeFromProgID(progId1);
            dynamic simpleobject = Activator.CreateInstance(type1);

            tbConsole.AppendText( simpleobject.HelloWorld());

            IConnectionPointContainer connectionPointContainer =
           simpleobject as IConnectionPointContainer;
            Guid guid = new Guid("014C067E-660D-4d20-9952-CD973CE50436");
            IConnectionPoint connectionPoint;
            connectionPointContainer.FindConnectionPoint(
                ref guid,
                out connectionPoint);


            //simpleobject.TextConsoleChanged += new Action(rinterface_ConsoleText);
            SimpleObjectEvents_SinkHelper sink =
            new SimpleObjectEvents_SinkHelper();

            // Connect the sink.
            int sinkCookie;
            connectionPoint.Advise(sink, out sinkCookie);

```

Error in the last line with:
System.Runtime.InteropServices.COMException: "Schnittstelle nicht unterstützt"
Schnittstelle nicht unterstützt

**Comment by avarghesein** [comment]
Dear viebrix, First of all thanks for your request. If I understood correctly, you would like to expose events from the ActiveX Server, which could be subscribed at clients (Say vb).

Now I presume, you could follow the same route, how your develop events in .NET COM Interops. My idea would be like this:

1. Create your Plugin DLL 
2. Have your events defined inside Plugin DLL: See below link on defining events
https://stackoverflow.com/questions/39511528/exposing-net-events-to-com
3. Now as an extra setup, generate a TLB file from your plugin DLL
https://docs.microsoft.com/en-us/dotnet/framework/tools/regasm-exe-assembly-registration-tool
4. Now keep your TLB file, unregister the plugin DLL
5. Now add your plugin dll, to the ActiveX.net server Plugin folder
6. Register the ActiveX Server
7. Import the TLB file in any vb client to get the events, and add event handlers
8. Run the client see, and see the events are fired and handled

This is just a thought popped out of my mind, and please do try the same and confirm back:

**Comment by avarghesein** [comment]
Dear viebrix, 

I got this working, as per the above steps. Please see below document, which will help you to understand the same. Please confirm back once you verify. Please take the latest of the solution, as I've done some minor modification on the source code. 

[Handling ActiveX Events in VB.docx](https://github.com/avarghesein/ActiveX.NET/blob/master/Handling%20ActiveX%20Events%20in%20VB.docx)

**Comment by viebrix** [comment]
Dear @avarghesein,

thank you so much! Now event handling is also working with my c# client. 
I'm not really sure, what did the trick - because I followed your steps and as I tried to use in my c# client project the created tlb file, visual studio told me that I can't add a link to a dotnet tlb file and I should instead include the ActiveX.NET.PLUGIN.RDOTNETCOM class.
But afterwards the event was found, and I could add my delegate like it would be a dotnet event:

```
string progId = "ActiveX.NET.Plugin.RDotnetCom";
Type type = Type.GetTypeFromProgID(progId);
RInstance1 = Activator.CreateInstance(type);
RInstance1.initEngine();
TextConsole_Delegate myDelegate = new TextConsole_Delegate(rinterface_ConsoleText);
RInstance1.TextConsole += myDelegate;

```
Maybe something in the registry changed with generating the tlb file, and therefore now adding the delegate worked? 

Beside, I also had to add the try and catch part (which you had already added in the RegistryUtility) in ActiveXServerBase.cs in RegasmRegisterLocalServer static function.

Thanks a lot for your help, I'm very happy that I can using events now without any problems!

**Comment by avarghesein** [comment]
Excellent viebrix. 

The issue was, by simply registering a COM dll, it might not be registering all types or its hierarchies, at least not known to the client. But if you register TLB, client will able to infer all types exposed by the server, and able to detect types. This is what happened when we used the TLB file. This could be done even without a TLB file, but you should be able to specifically declare the types in the client and which would be tedious. If you declare it incorrectly (might be in your initial case), the runtime will complain.

I could have been done registering TLB also with the ActiveX Server registration code, but TLB registration is not available through .NET API as per [this MSDN reference](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.registrationservices?view=netframework-4.8).

Between you could use [this TLB->DLL conversion](https://docs.microsoft.com/en-us/dotnet/framework/interop/how-to-generate-interop-assemblies-from-type-libraries), to refer a TLB exported types in a .NET project.

**Comment by viebrix** [comment]
@avarghesein everything works like a charm. Thank you so much! Now I'm able to use the com object in more instances with event handling and proper disposing.
Later on, I will try the tlb->dll conversion. The possibility sounds good, maybe intellisense will then work with the com methods. If not it's also no problem, because I know anyway, which methods I have implemented in the com object.
I'm very thankful for your great help. Now I'm able to implement the project I have in mind.

**Comment by avarghesein** [comment]
Thanks for confirming viebrix. Closing this thread, and marking as resolved. Glad to help!
